### PR TITLE
configure.ac: Fix Windows detection

### PR DESCRIPTION
**Pull request by ePirat**

### CODE REVIEW

**Comment by mrjimenez** [comment]
"#error" does not work with the windows compiler?

**Comment by ePirat** [comment]
It does not work reliable with some compilers, afaik. No clue which exactly, maybe only old ones we dont care about anymore but better be on the safe side this way…

**Comment by ePirat** [comment]
The more important change here is the `WIN32` to `_WIN32`.

**Comment by whyman** [comment]
Maybe add Windows to the new Github actions CI?

**Comment by ePirat** [comment]
I plan to do this. Adding a Windows build (on Windows using MSVC) is not possible right now though as the MSVC files are completely broken right now.

But I'll probably add cross-build using mingw-w64.

**Pull request merged**
