### PR TITLE
Extra Headers Improvements

### PR DESCRIPTION
**Pull request by v00d00**
- Rename ExtraHeaders to UpnpExtraHeaders
- Make UpnpExtraHeaders public (includes, exports)
- Populate the ExtraHeaders in the finfo passed to the VirtualDir get_info callback

With these patches I was sucessfully able to read and write extra headers from [my application](https://github.com/gerbera/gerbera).

Please review :+1:

### CODE REVIEW

**Comment by mrjimenez** [comment]
There is some pending "const" stuff, but overall awsome job!

**Comment by mrjimenez** [comment]
Should this work go into 1.8 or do we leave it only in master? I think it should go into 1.8, since it is ExtraHeaders stuff. The only issue (non-issue?) is that it adds stuff to the public API.

Opinions are welcome.

Regards,
Marcelo.

**Comment by v00d00** [comment]
Thanks for merging.

It should go into 1.8 for sure, as with the extra headers stuff.

**Comment by VVorttexx** [comment]
Well guys, are we finally going to be able to watch something on our Samsung TV? 
The NOT adding HTTP header is really frustrating.

**Pull request merged**
