### PR TITLE
Fix format string for ExtraHeaders

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Crashes Gerbera when creating response for file request

### CODE REVIEW

**Comment by whyman** [comment]
Why doesnt seem to crash on 1.8? It appears to be the the same code?

**Comment by KarlStraussberger** [comment]
Did not test it in 1.8.5. Possibly the same issue there also.
Only becomes active when ExtraHeaders are enabled.

**Comment by whyman** [comment]
Confirmed that the crash also happens in 1.8.5 :-1: 

But also that this patch fixes it there also :+1: 

@mrjimenez Can we have new releases, please :grin:

**Comment by mrjimenez** [comment]
> I've tested and confirmed that the crash also happens in 1.8.5 
> 
> But also that this patch fixes it there also 
> 
> @mrjimenez Can we have new releases, please

Sure!

**Pull request merged**
